language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 5.6
    - php: hhvm
    - php: 7.0
      env: DEPENDENCIES='dev'
    - php: 7.1
    - php: nightly
  allow_failures:
    - php: 7.1
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
   - bin/phpspec run --format=pretty
