version: '2'
services:
    app:
        build: ./app
        volumes:
          - ./../../../../../../../:/app
          - ./../../../../../../../var/cache:/app/var/cache
          - ./../../../../../../../var/logs:/app/var/logs
    php:
        build: ./php56
        volumes_from:
          - app
    web:
        build: ./nginx
        ports:
         - "8080:80"
        environment:
           - NGINX_PORT=80
        volumes_from:
          - app
